### ISSUE TITLE
Creating a new paste gives 'Not Valid Paste URL' exception

### ISSUE THREAD

**Issue by andrewlalis** [kennedyoliveira/pastebin4j#3]
I use the following code to execute a pastebin post.
```
PasteBin pasteBin = new PasteBin(new AccountCredentials(PASTEBIN_KEY));
Paste paste = new Paste(PASTEBIN_KEY);
paste.setTitle("Music Queue for Discord Server: "+guild.getName());
paste.setContent(sb.toString());
paste.setExpiration(PasteExpiration.ONE_HOUR);
paste.setVisibility(PasteVisibility.PUBLIC);
final String pasteURL = pasteBin.createPaste(paste);
```
However, I believe there is an issue with your `WebUtils.post` method, as it does not seem to be returning a proper URL despite being supplied with all the valid information as shown in your examples.

**Comment by kennedyoliveira** [comment]
Hello @andrewlalis , since you are authenticating with only the pastebin key, you are only allowed to list trend pastes and create guest pastes, to create a guest paste use `new GuestPaste(...)`.
Check the documentation on the constructor -> [Doc](http://kennedyoliveira.github.io/pastebin4j/javadoc/com/github/kennedyoliveira/pastebin4j/AccountCredentials.html#AccountCredentials-java.lang.String-)
